import React, { useState } from 'react';
import type { GeneratedMeme } from '../types';

interface MemeCardProps {
  meme: GeneratedMeme;
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
  onRegenerate: (id: string) => void;
  isRegenerating: boolean;
  isLoggedIn: boolean;
}

const MemeCard: React.FC<MemeCardProps> = ({ meme, onApprove, onReject, onRegenerate, isRegenerating, isLoggedIn }) => {
  const [isCopied, setIsCopied] = useState(false);
  const isPlaceholder = meme.imageUrl.includes('svg+xml');

  const getBorderColor = () => {
    if (!isLoggedIn) {
      return 'border-green-400 shadow-green-400/30';
    }
    switch (meme.status) {
      case 'approved':
        return 'border-green-400 shadow-green-400/30';
      case 'rejected':
        return 'border-red-500 shadow-red-500/30';
      default:
        return 'border-cyan-500/50';
    }
  };

  const handleShare = async () => {
    const shareText = `${meme.topText}\n${meme.bottomText}\n\nGenerated by Kiss My Face New York AI`;
    const shareData = {
      title: 'Kiss My Face New York Meme',
      text: shareText,
      url: window.location.href, // Shares a link back to the generator
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (error) {
        console.error('Error sharing:', error);
      }
    } else {
      // Fallback for browsers that do not support the Web Share API
      try {
        await navigator.clipboard.writeText(shareText);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000); // Reset after 2 seconds
      } catch (err) {
        console.error('Failed to copy text: ', err);
        alert('Failed to copy meme text.'); // Fallback for the fallback
      }
    }
  };

  const memeTextStyle = "absolute left-4 right-4 font-black uppercase text-center text-2xl md:text-3xl text-white [text-shadow:_2px_2px_4px_rgb(0_0_0_/_80%)] break-words";

  return (
    <div className={`bg-gray-900 rounded-lg overflow-hidden border-2 ${getBorderColor()} shadow-lg transition-all duration-300 hover:shadow-cyan-400/50 hover:-translate-y-1`}>
      <div className="relative">
        <img src={meme.imageUrl} alt={meme.altText} className={`w-full h-auto aspect-square object-cover transition-opacity ${isRegenerating ? 'opacity-30' : ''}`} />
        {isRegenerating && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/60">
            <div className="w-10 h-10 border-4 border-t-cyan-400 border-gray-600 rounded-full animate-spin"></div>
          </div>
        )}
        {!isPlaceholder && (
          <>
            <p className={`${memeTextStyle} top-4`}>{meme.topText}</p>
            <p className={`${memeTextStyle} bottom-4`}>{meme.bottomText}</p>
          </>
        )}
      </div>
      <div className="p-4 bg-gray-900/50">
        {isLoggedIn ? (
          // Admin View
          meme.status === 'pending' ? (
            <div className="flex justify-between items-center space-x-2">
              <button
                onClick={() => onApprove(meme.id)}
                disabled={isRegenerating}
                className="flex-grow bg-green-500/80 hover:bg-green-500 text-white font-bold py-2 px-3 rounded-lg transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                ✓ Approve
              </button>
              <button
                onClick={() => onRegenerate(meme.id)}
                disabled={isRegenerating}
                className="flex-shrink-0 bg-blue-500/80 hover:bg-blue-500 text-white font-bold p-3 rounded-lg transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
                aria-label="Regenerate image"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 110 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm12 8a1 1 0 011 1v3.101a7.002 7.002 0 01-11.601-2.566 1 1 0 111.885-.666A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1z" clipRule="evenodd" />
                </svg>
              </button>
              <button
                onClick={() => onReject(meme.id)}
                disabled={isRegenerating}
                className="flex-grow bg-red-600/80 hover:bg-red-600 text-white font-bold py-2 px-3 rounded-lg transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                × Reject
              </button>
            </div>
          ) : (
            <div className="flex items-center justify-between gap-4">
              <div className="text-center flex-grow">
                <p className={`font-bold text-xl uppercase tracking-widest ${meme.status === 'approved' ? 'text-green-400' : 'text-red-500'}`}>
                  {meme.status}
                </p>
              </div>
              {meme.status === 'approved' && (
                 <button
                  onClick={handleShare}
                  className="bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition-all duration-200 transform hover:scale-105 whitespace-nowrap"
                  aria-label="Share this meme"
                >
                  {isCopied ? 'Copied!' : '🔗 Share'}
                </button>
              )}
               {meme.status === 'rejected' && (
                <button
                  onClick={() => onRegenerate(meme.id)}
                  disabled={isRegenerating}
                  className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-lg transition-all duration-200 transform hover:scale-105 whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Regenerate
                </button>
              )}
            </div>
          )
        ) : (
          // Public/Viewer View
          <div className="text-center">
            <button
              onClick={handleShare}
              className="w-full bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition-all duration-200 transform hover:scale-105"
              aria-label="Share this meme"
            >
               {isCopied ? 'Copied!' : '🔗 Share'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default MemeCard;